name: Show DateTime

on: # Триггеры для запуска workflow
  push: # При пуше в любую ветку
    branches: [ '*' ]
  pull_request: # При создании или обновлении PR
    branches: [ 'main' ]

jobs:
  print-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Print current date
        run: |
          echo "Current date and time is: $(date)"
